bucket_volume: 1.5
cnn_input_size:
- 224
- 224
device: cpu
excavator: Экскаватор A
frame_rate: 5
last_project: data\09.06 20_43
project_name: default
use_cnn: false
video_path: C:/Users/Lev/Desktop/covsh/test/videos/11.mp4
yolo_conf_threshold: 0.5
